### ISSUE TITLE
filter out getmore operations

### ISSUE THREAD

**Issue by golonzovsky** [opentracing-contrib/java-mongo-driver#6]
It would be really useful to filter out `getmore` operations on `oplog.rs`. 

Oplog listeners create lots of noise with this:

![screenshot from 2019-02-13 18-15-16](https://user-images.githubusercontent.com/2477950/52730481-c1e65b80-2fbb-11e9-915f-f51403b56c15.png)

**Comment by malafeev** [comment]
fixed by https://github.com/opentracing-contrib/java-mongo-driver/pull/8
