### ISSUE TITLE
Custom span decoration

### ISSUE THREAD

**Issue by epkugelmass** [opentracing-contrib/java-mongo-driver#9]
Right now, span decoration is not modifiable without forking the library to change io.opentracing.contrib.mongo.common.TracingCommandListener#decorate

Clients should be able to supply a
```
@FunctionalInterface
interface SpanDecorator {
  void decorate(Span span, CommandStartedEvent event);
}
```
to customize this behavior.

What's the contribution policy for this project? I am more than happy to submit a PR.

**Comment by malafeev** [comment]
PR are welcome
